# Generated by Django 3.2 on 2021-04-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_todo_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='last_date',
            field=models.DateField(null=True, verbose_name="Yetiştirilme Tarihi 'Gün/Ay/Yıl'"),
        ),
    ]
